name: Daily Commit

on:
  schedule:
    - cron: "0 5 * * *"  # Runs every day at 05:00 UTC
  workflow_dispatch:  # allows manual runs if desired

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # IMPORTANT to allow push

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: "Daily commit by 24ds2000071@ds.study.iitm.ac.in"
        run: |
          echo "Daily commit timestamp: $(date -u)" >> daily-log.txt

          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          git add daily-log.txt
          git commit -m "Daily commit on $(date -u +'%Y-%m-%d %H:%M:%S')"
          git push
